apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-morty.fullname" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "rick-morty.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 5000
